### ISSUE TITLE
[Launch] Task list

### ISSUE THREAD

**Issue by beefchimi** [beefchimi/hardyfarms#2]
Here are the things left to complete:

- [ ] Grow section "less than 8" grid cell
- [ ] Squiggle animation
   - Remove `Bump.astro` if unused.
- [ ] Update all CTAs
   - Get Carson's email address
   - Consider using `secretEmail.ts`
- [x] 404 Page
- [ ] Remove unused assets
- [x] Remove unused CSS vars
- [x] Page load animation
   - Leverage existing `data-ready` attribute.
   - Reference Dulmage site for inspiration.
- [ ] Google Analytics
   - Set up new property
   - Add GA code
   - Test
- [ ] Get Carson's Twitter details.
   - If he doesn't want it, then remove all of the Twitter-related meta tags.
- [ ] Go over content with Carson
- [ ] Revisit all images
   - Include attributions.
   - Add alt text.
   - Crop to appropriate sizes.
   - Leverage Astro's responsive image API.
- [ ] Purchase domain
- [ ] Setup Netlify
   - Do I need a TOML file?

### Considerations

- [ ] Update anchor hash in URL while scrolling.
- [ ] Add CSS mixins.
- [ ] Should we move `wave-big.svg` to `/public`?
